// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var PhonicsApp$Phonics = require("./PhonicsApp.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(PhonicsApp$Phonics.make, { }), "app");

/*  Not a pure module */
