// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function toClassName(color) {
  switch (color) {
    case /* Orange */0 :
        return "orange";
    case /* Purple */1 :
        return "purple";
    case /* Yellow */2 :
        return "yellow";
    case /* Grey */3 :
        return "grey";
    case /* Pink */4 :
        return "pink";
    case /* Blue */5 :
        return "blue";
    
  }
}

var firstPhoneme = {
  sound: "a",
  image: "",
  color: /* Orange */0,
  side: /* Front */0
};

var orange_001 = /* :: */[
  {
    sound: "m",
    image: "",
    color: /* Orange */0,
    side: /* Front */0
  },
  /* :: */[
    {
      sound: "s",
      image: "",
      color: /* Orange */0,
      side: /* Front */0
    },
    /* :: */[
      {
        sound: "d",
        image: "",
        color: /* Orange */0,
        side: /* Front */0
      },
      /* :: */[
        {
          sound: "t",
          image: "",
          color: /* Orange */0,
          side: /* Front */0
        },
        /* [] */0
      ]
    ]
  ]
];

var orange = /* :: */[
  firstPhoneme,
  orange_001
];

var purple = /* :: */[
  {
    sound: "i",
    image: "",
    color: /* Purple */1,
    side: /* Front */0
  },
  /* :: */[
    {
      sound: "n",
      image: "",
      color: /* Purple */1,
      side: /* Front */0
    },
    /* :: */[
      {
        sound: "p",
        image: "",
        color: /* Purple */1,
        side: /* Front */0
      },
      /* :: */[
        {
          sound: "g",
          image: "",
          color: /* Purple */1,
          side: /* Front */0
        },
        /* :: */[
          {
            sound: "o",
            image: "",
            color: /* Purple */1,
            side: /* Front */0
          },
          /* [] */0
        ]
      ]
    ]
  ]
];

var yellow = /* :: */[
  {
    sound: "c",
    image: "",
    color: /* Yellow */2,
    side: /* Front */0
  },
  /* :: */[
    {
      sound: "k",
      image: "",
      color: /* Yellow */2,
      side: /* Front */0
    },
    /* :: */[
      {
        sound: "u",
        image: "",
        color: /* Yellow */2,
        side: /* Front */0
      },
      /* :: */[
        {
          sound: "b",
          image: "",
          color: /* Yellow */2,
          side: /* Front */0
        },
        /* [] */0
      ]
    ]
  ]
];

var grey = /* :: */[
  {
    sound: "f",
    image: "",
    color: /* Grey */3,
    side: /* Front */0
  },
  /* :: */[
    {
      sound: "e",
      image: "",
      color: /* Grey */3,
      side: /* Front */0
    },
    /* :: */[
      {
        sound: "l",
        image: "",
        color: /* Grey */3,
        side: /* Front */0
      },
      /* :: */[
        {
          sound: "h",
          image: "",
          color: /* Grey */3,
          side: /* Front */0
        },
        /* :: */[
          {
            sound: "sh",
            image: "",
            color: /* Grey */3,
            side: /* Front */0
          },
          /* [] */0
        ]
      ]
    ]
  ]
];

var pink = /* :: */[
  {
    sound: "r",
    image: "",
    color: /* Pink */4,
    side: /* Front */0
  },
  /* :: */[
    {
      sound: "j",
      image: "",
      color: /* Pink */4,
      side: /* Front */0
    },
    /* :: */[
      {
        sound: "v",
        image: "",
        color: /* Pink */4,
        side: /* Front */0
      },
      /* :: */[
        {
          sound: "y",
          image: "",
          color: /* Pink */4,
          side: /* Front */0
        },
        /* :: */[
          {
            sound: "w",
            image: "",
            color: /* Pink */4,
            side: /* Front */0
          },
          /* [] */0
        ]
      ]
    ]
  ]
];

var blue = /* :: */[
  {
    sound: "th",
    image: "",
    color: /* Blue */5,
    side: /* Front */0
  },
  /* :: */[
    {
      sound: "z",
      image: "",
      color: /* Blue */5,
      side: /* Front */0
    },
    /* :: */[
      {
        sound: "ch",
        image: "",
        color: /* Blue */5,
        side: /* Front */0
      },
      /* :: */[
        {
          sound: "qu",
          image: "",
          color: /* Blue */5,
          side: /* Front */0
        },
        /* :: */[
          {
            sound: "x",
            image: "",
            color: /* Blue */5,
            side: /* Front */0
          },
          /* :: */[
            {
              sound: "ng",
              image: "",
              color: /* Blue */5,
              side: /* Front */0
            },
            /* :: */[
              {
                sound: "nk",
                image: "",
                color: /* Blue */5,
                side: /* Front */0
              },
              /* [] */0
            ]
          ]
        ]
      ]
    ]
  ]
];

var phonemes = Pervasives.$at(orange, Pervasives.$at(purple, Pervasives.$at(yellow, Pervasives.$at(grey, Pervasives.$at(pink, blue)))));

function str(prim) {
  return prim;
}

function Phoneme(Props) {
  var phoneme = Props.phoneme;
  var match = Props.onClick;
  var onClick = match !== undefined ? match : (function (param) {
        return /* () */0;
      });
  return React.createElement("div", {
              className: "phoneme " + toClassName(phoneme.color),
              onClick: (function (_evt) {
                  return Curry._1(onClick, /* () */0);
                })
            }, phoneme.sound);
}

var make = Phoneme;

exports.toClassName = toClassName;
exports.firstPhoneme = firstPhoneme;
exports.orange = orange;
exports.purple = purple;
exports.yellow = yellow;
exports.grey = grey;
exports.pink = pink;
exports.blue = blue;
exports.phonemes = phonemes;
exports.str = str;
exports.make = make;
/* phonemes Not a pure module */
