// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Phoneme$Phonics = require("./Phoneme.bs.js");

function str(prim) {
  return prim;
}

function reducer(state, action) {
  return state;
}

function View(Props) {
  Props.dispatch;
  var state = Props.state;
  var onEditButtonClicked = Props.onEditButtonClicked;
  var View$1 = function (Props) {
    var phonemes = Props.phonemes;
    return React.createElement("div", {
                className: "phonemes"
              }, $$Array.of_list(List.mapi((function (index, phoneme) {
                          return React.createElement(Phoneme$Phonics.make, {
                                      phoneme: phoneme,
                                      key: String(index)
                                    });
                        }), phonemes)));
  };
  return React.createElement("div", {
              className: "view"
            }, React.createElement(View$1, {
                  phonemes: state.phonemes
                }), React.createElement("button", {
                  className: "view-button",
                  onClick: (function (_evt) {
                      return Curry._1(onEditButtonClicked, /* () */0);
                    })
                }, "Edit"));
}

var make = View;

exports.str = str;
exports.reducer = reducer;
exports.make = make;
/* react Not a pure module */
