name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        node-version: '10.x'
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Publish
      uses: maxheld83/ghpages@v0.2.1
      env:
        BUILD_DIR: "dist/"
