name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        node-version: '10.x'
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Publish
      if: success()
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: dist
      env:
        GITHUB_PAT: ${{ secrets.GH_PAT }}
